name = "killurl"
type = "webpack"
account_id = "***REMOVED***"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"
kv_namespaces = [ 
         { binding = "LINKS", id = "***REMOVED***", preview_id = "***REMOVED***" }
]